### ISSUE TITLE
Remove mutable requirement in Model.forward

### ISSUE THREAD

**Issue by xtuc** [huggingface/candle#1044]
I'm copying the Mistral example and I noticed that [Model.forward](https://docs.rs/candle-transformers/0.3.0/candle_transformers/models/quantized_mistral/struct.Model.html#method.forward) is taking a `&mut self`.

To be able to cache and reuse the model, it would be better to remove `mut`. It sounds like mutability is only needed for an internal KV cache, ideally, it would be wrapped into a Mutex and the model being responsible for resetting the cache after a completed request.

**Comment by LaurentMazare** [comment]
I don't think it's that clear cut, some of our models do use a mutex for the kv cache, some prefer `&mut` and having written models with both, I find that both have tradeoffs, so it's a bit up to the model implementor to decide what they prefer (at this stage it seems better to explore the alternatives rather than trying to be uniform).
When it comes to reseting the cache, the LLMs are mostly used in a streaming way so the model itself doesn't have a good way to know the request is actually finished (we could infer it based on position-ids in some cases but seems hacky). Because of this, some models have an explicit `reset_kv_cache` method but again this has some tradeoffs and it's unclear that it's what we should have everytwhere.

**Comment by juspky** [comment]
I also tried caching the mistral model and the `mut` on `Model.forward` is giving me headaches.

I really don't know how to make a model available to different threads without running `VarBuilder.from_...` and `Mistral::new` everytime to make a new `Model` that gets moved into the thread, which takes too long.

**Comment by LaurentMazare** [comment]
> I really don't know how to make the model available to different threads without running `VarBuilder.from_...` and `Mistral::new` everytime to make a new `Model` that gets moved into the thread, which takes too long and is resource heavy.

I just merged #1125 that makes a couple models including mistral cloneable. Cloning should be reasonably cheap as it doesn't duplicate the tensor data. Could you give this a spin and let us know how it goes?
It's certainly more of an experiment at this stage, based on your feedback and on how this impacts other users we could decide to extend this to other models (or find another way to allow for multiple threads)

**Comment by juspky** [comment]
Amazaing, this seems to be  exactly what I needed. Can you put the Clone trait on QMistral too?
It seems to be the last thing that keeps me from making it work.

**Comment by LaurentMazare** [comment]
Yes QMistral should be fine (this requires a bit of checking for each model as we want to avoid the ones that have mutex protected states or similar), done in #1126.

**Comment by juspky** [comment]
Thanks for coming up with a solution this quick!

I gave it a spin, cloning the model takes only a few ns and using the cloned model in multiple threads worked well too. 
```
loaded the model in 2.000470125s (from file)
loaded the model in 791ns (using clone)
loaded the model in 541ns (using clone)
```

**Comment by LaurentMazare** [comment]
Closing this as done but feel free to reopen or create a new issue if you have further questions.
