### ISSUE TITLE
Concurrent Model Access Across Multiple Functions

### ISSUE THREAD

**Issue by okpatil4u** [huggingface/candle#1059]
Is it possible to multiple functions to access the same model ? As per my understanding, the model is loaded once in read only format, where calculations happen in individual functions with their individual contexts.

This could be a huge memory save. Can this be done ?

**Comment by LaurentMazare** [comment]
It depends on the model and the functions that you want to run on it. A possible limitation would be the KV cache, for the currently implemented models that have such a cache, the cache is unique so if you were to run multiple inferences on the same model but without using the batch dimension for that, this could be an issue.
If this is annoying for your use case, a simple fix would likely be to clone the model which would be fairly cheap (as all the actual weights are behind some `Arc`), alternatively you can try using some explicit kv-cache passed as parameters rather than what we currently do storing the cache in the model.

**Comment by okpatil4u** [comment]
Yes, that makes sense. Thank you.
