### ISSUE TITLE
Phi example panics with an empty prompt

### ISSUE THREAD

**Issue by ealmloff** [huggingface/candle#1095]
The phi example panics when you feed in an empty prompt:
```rust
cargo run --example phi --release -- --prompt ""
```
Error produced:
```
avx: false, neon: true, simd128: false, f16c: false
temp: 0.00 repeat-penalty: 1.10 repeat-last-n: 64
retrieved the files in 745.75µs
Running on CPU, to run on GPU, build this example with `--features cuda`
loaded the model in 1.848781375s
starting the inference loop
thread 'main' panicked at candle-core/src/shape.rs:648:12:
attempt to calculate the remainder with a divisor of zero
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:117:5
   3: <(usize,usize,usize,(),usize) as candle_core::shape::ShapeWithOneHole>::into_shape
   4: candle_core::tensor::Tensor::reshape
   5: candle_transformers::models::mixformer::MixFormerSequentialForCausalLM::forward
   6: phi::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Platform information:
`rustc 1.73.0`
`MacOs (m2)`

I'm not sure if the model can run with an empty prompt. If not I would be happy to add a better error message when the prompt is empty

**Comment by LaurentMazare** [comment]
Fwiw the python version also doesn't work with an empty prompt and I think that's all due to the specific tokenizer that phi uses which doesn't have a 'start of sequence' tokens. I'll tweak the underlying error messages to make them a bit better.
'''python
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

torch.set_default_device("cuda")
model = AutoModelForCausalLM.from_pretrained("microsoft/phi-1_5", trust_remote_code=True)
tokenizer = AutoTokenizer.from_pretrained("microsoft/phi-1_5", trust_remote_code=True)
inputs = tokenizer('', return_tensors="pt", return_attention_mask=False)

outputs = model.generate(**inputs, max_length=200)
text = tokenizer.batch_decode(outputs)[0]
```

```
untimeError: cannot reshape tensor of 0 elements into shape [-1, 0] because the unspecified dimension size -1 can be any value and is ambiguous
```

**Comment by LaurentMazare** [comment]
Closing this now but feel free to re-open if some bits are still missing (or open a new issue).
