### ISSUE TITLE
Optimizing Azure VM Selection for Cost-Effective Deployment of Candle LLMs

### ISSUE THREAD

**Issue by ScottLL** [huggingface/candle#1229]
Hello,
I'm a graduate student from Duke University, collaborating with Professor Noah [noahgift](https://github.com/noahgift) on the Candle project. I believe he has already reached out to you earlier (you can see the details [here](https://github.com/huggingface/candle/issues/642#issuecomment-1786831092)).

We're currently encountering an issue as we're setting up an Azure Virtual Machine to act as the Azure Spot Runner for Github Actions, with the purpose of running the Candle binary. We would greatly appreciate your insights on selecting the most cost-effective Cuda-enabled VM on Azure for this task.

Thank you.

**Comment by LaurentMazare** [comment]
Hello,
I'm afraid I don't know anything about azure. Are there some candle specific parts to your problem, e.g. an error message that we could look at? Otherwise I would suggest going for the same thing as people would for running PyTorch models on azure and hopefully that should work for candle too.

**Comment by ScottLL** [comment]
Cool, I will proceed to identify a suitable CUDA-enabled virtual machine for this purpose then, will keep you updated. Thank you!

**Comment by LaurentMazare** [comment]
Closing this for now as hopefully you will have sorted things out now.
