### ISSUE TITLE
Missing upper&lower triangular

### ISSUE THREAD

**Issue by mokeyish** [huggingface/candle#1256]
I found that candle was missing triangular, 
so I implemented it myself. It would be better if candle could be built-in, but I don't know what you think about this implementation. 

If possible, I can submit a PR to this repository.

![image](https://github.com/huggingface/candle/assets/16131917/8ec65604-e72c-4186-92f1-ecff8b41741e)

**Comment by mokeyish** [comment]
Now, I have temporarily added tril/triu and the like to my own repository. https://github.com/mokeyish/candle-ext

**Comment by LaurentMazare** [comment]
Looks nice, do you want to add a link to candle-ext in the [external resources section](https://github.com/huggingface/candle#useful-external-resources) of the readme? That would make it easier for potential users to discoer.

**Comment by mokeyish** [comment]
Of course, I'll add it.

**Comment by mokeyish** [comment]
I've add it, please review the PR #1277 .

**Comment by LaurentMazare** [comment]
Merged, thanks a lot, and we'll see over time if we move some functions to `candle-nn` vs just having them on `candle-ext`, at this stage it's good that you can iterate quickly on `candle-ext` and have everything that you need readily available.

**Comment by LaurentMazare** [comment]
Actually I've put some implementation for `tril2`, `triu2`, and `eye` in #1333 that should be a bit lower level than `tril` and `triu` but can be used to implement them in a differentiable way (just doing a pointwise multiplication with the output of `tril2` and `triu2`). They should also be reasonably efficient (though this can certainly be improved but at least it should avoid moving too much data between the gpu and the host). The main motivation is so that they can be used for some other lower level ops that I will push in a follow up PR.
