### ISSUE TITLE
Image Processor

### ISSUE THREAD

**Issue by ToluClassics** [huggingface/candle#1289]
Hi @LaurentMazare ,

I have been putting together an Image processor similar to [ViTImageProcessor](https://github.com/huggingface/transformers/blob/1b20e2bb421175270d625a9610ebaa00c445fcb4/src/transformers/models/vit/image_processing_vit.py#L41C7-L41C24) that can be used to process image inputs to different inputs. I see that image processing is implemented differently for different models 

it looks something like this
```rust
let config = ProcessorConfig::default();
let processor = ImageProcessor::new(&config);

let output: Vec<Tensor> = processor.process(images)
```

Would it be something you'd like merged in here?

**Comment by LaurentMazare** [comment]
We don't have a very good place to put these at the moment. In `candle-transformers` we try to avoid having too many dependencies hence we don't have a dependency on `image` or `image-proc` and don't do anything image specific in there. In `candle-examples` we have some function to load and resize pictures so that they are in imagenet format and can be used by our computer vision examples.
I'm not sure what other functionalities your image processors provide but to me they most would probably be nice to have in some external repo next to the models that actually end up using them. At some point such functions might be good to consolidate in some shared place but it's hard to know really what will stick at this point so better to see once you've put out the models and processors how they endup being re-used and the feedback that they might gather from possible end users.

**Comment by ToluClassics** [comment]
Fair enough, I'll close this then

**Comment by LaurentMazare** [comment]
Forgot to mention it but very curious about how you end up using this, so please give a link once there is a model repo or whatever.

**Comment by ToluClassics** [comment]
For sure, I'll share a link
