### ISSUE TITLE
model sharing in  multi-threaded scenario [Question]

### ISSUE THREAD

**Issue by a-agmon** [huggingface/candle#1519]
I have a question about the best practice with Candle for inference services. 
In the multi-threaded scenario, since models are required to be mutable, stateful, and used to run inference loops, it seems that models cant be shared by threads.
what is the best practice in a high throuput scenario? 
loading the model once at bootstrap and cloning it for each new request to ge a fresh copy?

**Comment by LaurentMazare** [comment]
Models that have a mutable `forward` method usually do so because they embed a kv cache so it wouldn't be safe to use them to run multiple inference runs in parallel. The best for these is usually to clone the model for each thread (which should be lightweight as the weights will be shared), and then for each thread when processing a request, reset the kv cache and generate the data for this request.
Models that don't have an inner kv cache usually have a non mutable `forward` so can be used across threads without any precaution as they are stateless.

**Comment by a-agmon** [comment]
Thanks @LaurentMazare , 
thats very helpful. What is the appropriate way to reset the kv cache on a model. I couldnt find it in the code. (Im using models from the candle_transformers::models crate)

**Comment by LaurentMazare** [comment]
> What is the appropriate way to reset the kv cache on a model. I couldnt find it in the code.

It's a bit model dependent, for some of them it's called `reset_kv_cache` and for others `clear_kv_cache`.

**Comment by a-agmon** [comment]
Thanks @LaurentMazare 
This works
