### ISSUE TITLE
Why is the answer of my Gemma example not as expected? Did I miss something?

### ISSUE THREAD

**Issue by coolbeevip** [huggingface/candle#2170]
```shell
./gemma  --prompt="How to write a good article"
avx: false, neon: true, simd128: false, f16c: false
temp: 0.00 repeat-penalty: 1.10 repeat-last-n: 64
retrieved the files in 9.415834ms
Running on CPU, to run on GPU(metal), build this example with `--features metal`
loaded the model in 10.446127666s
How to write a good article title?

In the following sentence, underline the correct modifier from the pair given in parentheses. Example 1. He is (real, $\underline{\text{really}}$) talented at fixing cars.

I’m <em>(slow, slowly)</em> to understand geometrical concepts.

What was the purpose of the Dawes Act?

In each of the following sentences, underline the correct form of the adjective or adverb in parentheses.

<strong>Example 1</strong>. This fireworks display is (impressiver, $\underline{{more~ impressive}}$) than last year’s was.

Samantha did a lot <em>(well, better)</em> on her test than she thought she would.
142 tokens generated (3.18 token/s)
```

**Comment by soupslurpr** [comment]
I think the issue is with your prompt, perhaps try something like this as the prompt:

~~~
Q: How to write a good article?

A:
~~~

**Comment by coolbeevip** [comment]
New question, repeatedly output `The first thing you need ...` 

```shell
./gemma  --prompt="Q: How to write a good article?

A:"
avx: false, neon: true, simd128: false, f16c: false
temp: 0.00 repeat-penalty: 1.10 repeat-last-n: 64
retrieved the files in 9.756ms
Running on CPU, to run on GPU(metal), build this example with `--features metal`
loaded the model in 15.227936292s
Q: How to write a good article?

A: The first thing you need to do is find a topic that interests you. Once you have a topic, you need to research it thoroughly. This means reading books, articles, and other sources of information on the topic. You should also interview experts in the field to get their opinions. Once you have all of this information, you can start writing your article.

The first thing you need to do is find a topic that interests you. Once you have a topic, you need to research it thoroughly. This means reading books, articles, and other sources of information on the topic. You should also interview experts in the field to get their opinions. Once you have all of this information, you can start writing your article.

The first thing you need ....
```

**Comment by soupslurpr** [comment]
A better way to prompt it is the following, state the question in a way where the model is posed to answer it:

~~~
Heres how you can write a good article:
~~~

it responds with the following for me (running recurrentgemma-2b-q8_0.gguf:

~~~
Heres how you can write a good article:

1. Write an introduction that grabs the readers attention and sets up the topic of your article.
2. Provide a brief overview of the main points in your article, but don't give away too much information.
3. Use examples to illustrate your points and make them more relatable for your audience.
4. End with a call-to-action that encourages readers to take action on what you've discussed.

Remember: The goal of an article is not just to inform, but also to persuade the reader to take action or change their mind in some way. So be sure to include strong arguments and evidence throughout your writing!
~~~


If the answer is too short, you can modify the prompt so that it gives a longer and more detailed answer:

~~~
Heres a very long and detailed guide on how you can write a good article:
~~~

Hope this helps and good luck!

**Comment by coolbeevip** [comment]
> A better way to prompt it is the following, state the question in a way where the model is posed to answer it:
> 
> ```
> Heres how you can write a good article:
> ```
> 
> it responds with the following for me (running recurrentgemma-2b-q8_0.gguf:
> 
> ```
> Heres how you can write a good article:
> 
> 1. Write an introduction that grabs the readers attention and sets up the topic of your article.
> 2. Provide a brief overview of the main points in your article, but don't give away too much information.
> 3. Use examples to illustrate your points and make them more relatable for your audience.
> 4. End with a call-to-action that encourages readers to take action on what you've discussed.
> 
> Remember: The goal of an article is not just to inform, but also to persuade the reader to take action or change their mind in some way. So be sure to include strong arguments and evidence throughout your writing!
> ```
> 
> If the answer is too short, you can modify the prompt so that it gives a longer and more detailed answer:
> 
> ```
> Heres a very long and detailed guide on how you can write a good article:
> ```
> 
> Hope this helps and good luck!

Thank you. 

I found official recommendations here: https://huggingface.co/google/gemma-7b/discussions/14
