### ISSUE TITLE
Using your own fine tuned weights

### ISSUE THREAD

**Issue by tanakachitsamba** [huggingface/candle#444]
How do you provide a path to your own fine tuned weights for all the other models but its clear how you do it for llama2 but not the other models.

**Comment by LaurentMazare** [comment]
This varies a bit from one model to another (these should more be considered as examples of how to use candle rather than finished products). E.g. for something like whisper, you can use the [model_id flag](https://github.com/huggingface/candle/blob/c84883ecf2c240792392353175b634f6ec92a011/candle-examples/examples/whisper/main.rs#L282) to point it at some specific model repo on the huggingface hub where it will take its configuration from. Do you have a specific model in mind?

**Comment by LaurentMazare** [comment]
Closing this now, feel free to re-open if you run into further issues.
