### ISSUE TITLE
Specify the device only once

### ISSUE THREAD

**Issue by timokoesters** [huggingface/candle#446]
This looks like a great project!

I have a question: Why is it necessary to specify the device for every Tensor? Wouldn't it be possible to set the device once and then all allocations are made to that device?
This would work like a global allocator in Rust: https://doc.rust-lang.org/std/alloc/index.html

The drawback is that you can't use multiple backends at the same time easily.

What are your thoughts?

**Comment by LaurentMazare** [comment]
That's an interesting idea. I would think that `candle-core` is a pretty low-level api so should provide the flexibility to provide different devices whereever needed (and it's actually not to bad as it's only when creating new tensors from scratch that it's needed, not when applying operations on tensors), but you could imagine having higher-level crates that use `candle-core` and provide more ergonomics such as handling the device for you etc. So I would encourage you to give a try at writing such higher level crates and experimenting with this kind of ideas, it would be very interesting to get your feedback/experience return if you do so.

**Comment by LaurentMazare** [comment]
Closing this for now as probably nothing actionable at the moment. Feel free to create further issues for suggestions/... (or go to the discord channels for discussion).

**Comment by LaurentMazare** [comment]
That could indeed be done but I'm not super thrilled by the idea of duplicating lots of functions, we already have a bunch of functions with multiple variants because of default parameters and it's a bit of a pain. After having implemented quite a few models I find that being explicit about the device hasn't introduced that much churn in the code (using the var-builder to retrieve the device to be used), that said if you have some code where you find that it's actually messy I'm certainly happy to look at it.
