### ISSUE TITLE
Need train example

### ISSUE THREAD

**Issue by evgenyigumnov** [huggingface/candle#637]
Could you add the following case to the examples?

Take the llama model (from llama example) as a basis and train it on a simple dataset from a file.
For example:
[
  {
  "input": "What is your name?", "output": "What is your name? My name is ROBOTRON"
  },
  {
  "input": "How old are you?", "output": "How old are you? I am immortal robot!"
  },
]

Then we run the trained model and submit file for the test as input and print the result of the test work on stdout.
For example (file)
[
  {
  "test": "Hello! What is your name?"
  },
  {
  "test": "Good morning! How old are you?"
  },
]
For example (stdout)
test 1:
Hello! What is your name? Hello my friend. I am ROBOTRON.
test 2:
Good morning! How old are you? Good morning. I am no age robot!

**Comment by evgenyigumnov** [comment]
If is not so hard. You could explain me how to do this. And I add this example by myself to you repository.

**Comment by evgenyigumnov** [comment]
As I seen in README.md

- Simple syntax, looks and feels like PyTorch.
    - Model training.

**Comment by evgenyigumnov** [comment]
https://github.com/huggingface/candle/tree/main/candle-book/src/training
Thats all what I found :( 

I understand the importance of idiomatic learning examples on handwriting recognition. But somehow everyone wants to retrain language models. I beg you. Although you did not help me with servers with video cards. Give at least links to articles or contacts of people that would explain how to do this.

**Comment by HoodieCollin** [comment]
Hey there, I've been looking for the same resources and sadly I haven't had much luck finding a “walk-through” on how to train a model with Candle (I assume it's too young of a project for there to be blogs and more fleshed-out tutorials).

If you are like me and new to ML in general but a seasoned programmer, I recommend the following process while we wait for improved docs.

- Find a tutorial that uses PyTorch or Tensorflow to build and train a simple model on the MNIST dataset.
- Follow that guide and experiment with it in a Google Collab notebook.
- Ask ChatGPT to clarify anything you don't understand (the MNIST dataset is classic so ChatGPT has a good understanding of the concepts involved).

Now that you have a good grasp of how that specific implementation works, go to the examples workspace in this repo. You should inspect the MNIST example and compare it to the Python version you just finished. [Here is a link to the example.](https://github.com/huggingface/candle/blob/main/candle-examples/examples/mnist-training/main.rs)

I know this isn't exactly what you were looking for since it targets image data vs. text data but I hope this helps you get started. You can take the learnings from this process and try to apply it to the Llama transformer implementation.

PS. If you have access to ChatGPT-4, which has a decent understanding of Rust and its ecosystem (up to 2021), you can also prompt it with the code from the example I linked above and ask it for insight into how it relates to the Python implementation.

**Comment by evgenyigumnov** [comment]
Thanks for the advice. But I passed the stage you described above a long time ago. The result was this 

[https://github.com/evgenyigumnov/candle-simplified-example](https://github.com/evgenyigumnov/candle-simplified-example)

**Comment by HoodieCollin** [comment]
Thanks for sharing! Your example has been helpful.

**Comment by Narsil** [comment]
@evgenyigumnov that' s a really neat example ! 

Would you like to include it in the book ? 
I think your example is super simple and could come before: 
https://huggingface.github.io/candle/training/mnist.html

**Comment by evgenyigumnov** [comment]
> @evgenyigumnov that' s a really neat example !
> 
> Would you like to include it in the book ? I think your example is super simple and could come before: https://huggingface.github.io/candle/training/mnist.html

Yes, include my example in the book. I will be pleased.

**Comment by evgenyigumnov** [comment]
Sorry. Maybe we have a misunderstanding. Perhaps you expected me to make a pull request for the book myself? I can do it

**Comment by Narsil** [comment]
Both would work ! 

If you have time to do the PR it would be highly appreciated !

**Comment by evgenyigumnov** [comment]
Pull request created )

**Comment by crazyn2** [comment]
Can it provide a example with dataset downloaded automatically and training?

**Comment by LaurentMazare** [comment]
Closing stale issues, feel free to open a fresh one if you're still having problems.
