### ISSUE TITLE
Neural network automatic conversion tool

### ISSUE THREAD

**Issue by bigpo** [huggingface/candle#906]
I see the great potential of candle and appreciate the effort of the authors. Is it possible to provide a conversion tool that can convert a PyTorch version of a network into a Candle version? If possible, that would bring tremendous convenience.

**Comment by Narsil** [comment]
You can check our examples.

It' s not zero work, but it should be decently easy (we' ve done it quite a few times by now).

There's never going to be a drop-in autoconvert, simply because it's not possible (Python being python is by definition extremely versatile, where as rust is compiled and requires much more structure in the code itself. the typings for starts need to be fixed, which is not possible in transformers that changes return types based on inputs).

Also in our experience, when we're using candle it's for specific workloads for which we usually write the modeling code differently than `transformers` (is it CPU-only, GPU-only, flash/no-flash, is batching interesting ?).
Never any major differences, but things that can end up making a difference in production.
